<?php
$modversion['name'] = "zenTrackXoops";
$modversion['version'] = "2.604";
$modversion['description'] = "zenTrackXoops 2.6.0.4 HelpDesk";
$modversion['author'] = "http://zentrack.sourceforge.net/";
$modversion['credits'] = "Sqeezed into XOOPS and enhanced by Duncan Keir based in original 2.3.2 version by Wang Jue (aka wjue) (http://www.guanxiCRM.com, http://www.wjue.org) ";
$modversion['help'] = "";
$modversion['license'] = "GPL";
$modversion['official'] = 1;
$modversion['image'] = "images/zenTrackxoops_logo.jpg";
$modversion['dirname'] = "zentrack";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "zentrack_access";
$modversion['tables'][1] = "zentrack_attachments";
$modversion['tables'][2] = "zentrack_bins";
$modversion['tables'][3] = "zentrack_logs";
//$modversion['tables'][4] = "zentrack_logs_archived";
$modversion['tables'][5] = "zentrack_preferences";
$modversion['tables'][6] = "zentrack_priorities";
$modversion['tables'][7] = "zentrack_reports";
$modversion['tables'][8] = "zentrack_reports_index";
$modversion['tables'][9] = "zentrack_reports_temp";
$modversion['tables'][10] = "zentrack_settings";
$modversion['tables'][11] = "zentrack_systems";
$modversion['tables'][12] = "zentrack_tasks";
$modversion['tables'][13] = "zentrack_tickets";
//$modversion['tables'][14] = "zentrack_tickets_archived";
$modversion['tables'][15] = "zentrack_types";
$modversion['tables'][16] = "zentrack_users";
$modversion['tables'][17] = "zentrack_notify_list";

$modversion['tables'][18] = "zentrack_behavior";
$modversion['tables'][19] = "zentrack_behavior_detail";
$modversion['tables'][20] = "zentrack_group";
$modversion['tables'][21] = "zentrack_group_detail";
$modversion['tables'][22] = "zentrack_varfield";
$modversion['tables'][23] = "zentrack_varfield_idx";
$modversion['tables'][24] = "zentrack_varfield_multi";
$modversion['tables'][25] = "zentrack_agreement";
$modversion['tables'][26] = "zentrack_agreement_item";
$modversion['tables'][27] = "zentrack_company";
$modversion['tables'][28] = "zentrack_employee";
$modversion['tables'][29] = "zentrack_related_contacts";
$modversion['tables'][30] = "zentrack_field_map";
$modversion['tables'][31] = "zentrack_view_map";

//$modversion['tables'][32] = "zentrack_translation_strings";
//$modversion['tables'][33] = "zentrack_translation_words";



// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/admin_index.php";
$modversion['adminmenu'] = "admin/menu.php";
// Blocks
//$modversion['blocks'][1]['file'] = "";
//$modversion['blocks'][1]['name'] = _MI_ZENTRACKXOOPS_BNAME1;
//$modversion['blocks'][1]['description'] = "";
//$modversion['blocks'][1]['show_func'] = "b_zentrackxoops_newshow";
//$modversion['blocks'][1]['edit_func'] = "b_zentrackxoops_newedit";
//$modversion['blocks'][1]['template'] = 'zentrackxoops_block_new.html';
//$modversion['blocks'][1]['options'] = '';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'zentrack_index.html';
$modversion['templates'][1]['description'] = '';




?>
