#!/bin/sh

mkdir includes/attachments
mkdir includes/logs
mkdir includes/cache
mkdir includes/users
mkdir includes/user_data

cp -ib install/configVars.php.default includes/configVars.php
cp -ib install/header.php.default www/header.php
cp -ib install/egate_config.php.default includes/egate_config.php

chmod 777 includes/attachments
chmod 777 includes/logs
chmod 777 includes/cache
chmod 777 includes/translations
chmod -R 755 www/images
chmod 755 www/javascript.js
chmod 755 www/styles.php
chmod 755 includes/egate_check.php
chmod 755 includes/egate.php
chmod 755 includes/users